name: chargeio
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.3.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  easy_sidemenu: ^0.4.1
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  firebase_dart: ^1.0.11
  flutter:
    sdk: flutter
  fluttertoast: ^8.1.2
  hexcolor: ^3.0.1
  mqtt_client: ^9.7.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
